packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'examples/*'
  # exclude packages that are inside test directories
  - '!**/test/**'

catalog:
  typescript: 5.9.2

engineStrict: true
nodeVersion: 20.19.4
