import { CE_COMMAND } from '#/interfaces/CE_COMMAND';
import type { TFrameCommandArgv } from '#/interfaces/IFrameCommandArgv';
import { coercePathOrUrl } from '#/validators/coercePathOrUrl';
import { getCoercePath } from '#/validators/getCoercePath';
import type { Argv } from 'yargs';

export function frameCommandBuilder(argv: Argv<TFrameCommandArgv>): Argv<TFrameCommandArgv> {
  argv
    .option('action', {
      type: 'string',
      default: CE_COMMAND.FRAME,
      hidden: true,
    })
    .positional('spec', {
      type: 'string',
      demandOption: true,
      describe: 'Path to the OpenAPI specification file (JSON or YAML)',
      coerce: coercePathOrUrl,
    })
    .option('type', {
      type: 'string',
      demandOption: true,
      describe: 'Path to the TypeScript type definition file generated by openapi-typescript',
      coerce: getCoercePath({ kind: 'file', name: '--type' }),
    });

  return argv;
}
