import type { Argv } from "yargs";
import { CE_COMMAND } from "#src/interfaces/CE_COMMAND.js";
import type { TFrameCommandArgv } from "#src/interfaces/IFrameCommandArgv.js";
import { coercePathOrUrl } from "#src/validators/coercePathOrUrl.js";
import { getCoercePath } from "#src/validators/getCoercePath.js";

export function frameCommandBuilder(argv: Argv<TFrameCommandArgv>): Argv<TFrameCommandArgv> {
  argv
    .option("action", {
      type: "string",
      default: CE_COMMAND.FRAME,
      hidden: true,
    })
    .positional("spec", {
      type: "string",
      demandOption: true,
      describe: "Path to the OpenAPI specification file (JSON or YAML)",
      coerce: coercePathOrUrl,
    })
    .option("type", {
      type: "string",
      demandOption: true,
      describe: "Path to the TypeScript type definition file generated by openapi-typescript",
      coerce: getCoercePath({ kind: "file", name: "--type" }),
    });

  return argv;
}
