import type { DedupeResult } from '#interfaces/DedupeResult';

interface BufferedResponse {
  status: number;
  statusText: string;
  headers: Headers;
  body: string;
}

/**
 * Manages request deduplication to prevent multiple identical HTTP requests
 * from being sent simultaneously. When multiple requests with the same cache key
 * are made, only the first request is actually sent, and all subsequent requests
 * receive the same response.
 *
 * The cache key is generated using the `getCacheKey()` method from JinFrame instances,
 * which creates a unique identifier based on the request parameters and configuration.
 */
export class RequestDedupeManager {
  /** Store pending requests (key: cacheKey, value: Promise of buffered response) */
  private static pendingRequests = new Map<string, Promise<BufferedResponse>>();

  /**
   * Deduplicates HTTP requests based on cache key. If a request with the same
   * cache key is already in progress, returns the result of that request.
   * Otherwise, executes the new request and stores it for potential deduplication.
   *
   * @template Pass - The expected response data type
   * @param cacheKey - Unique identifier for the request used for deduplication (generated by JinFrame.getCacheKey())
   * @param requesterFn - Function that performs the actual HTTP request
   * @returns Promise resolving to DedupeResult containing the response and deduplication flag
   *
   * @example
   * ```ts
   * // Cache key is typically generated by JinFrame.getCacheKey()
   * const frame = GetUserFrame.of({ id: '123' });
   * const cacheKey = frame.getCacheKey();
   *
   * const result = await RequestDedupeManager.dedupe(
   *   cacheKey,
   *   () => axios.get('/users/123')
   * );
   * console.log(result.isDeduped); // false for original request, true for duplicates
   * ```
   */
  static async dedupe(cacheKey: string, requesterFn: () => Promise<Response>): Promise<DedupeResult> {
    const existingPromise = this.pendingRequests.get(cacheKey);
    if (existingPromise) {
      const buffered = await existingPromise;
      const resp = new Response(buffered.body, { status: buffered.status, statusText: buffered.statusText, headers: buffered.headers });
      return { resp, isDeduped: true };
    }

    // Buffer the response so multiple callers can each read the body independently
    const promise = requesterFn()
      .then(async (reply) => {
        const body = await reply.text();
        this.pendingRequests.delete(cacheKey);
        return { status: reply.status, statusText: reply.statusText, headers: reply.headers, body } satisfies BufferedResponse;
      })
      .catch((error: unknown) => {
        this.pendingRequests.delete(cacheKey);
        throw error;
      });

    // Prevent race condition: register promise immediately after creation
    this.pendingRequests.set(cacheKey, promise);

    const buffered = await promise;
    const resp = new Response(buffered.body, { status: buffered.status, statusText: buffered.statusText, headers: buffered.headers });
    return { resp, isDeduped: false };
  }

  /**
   * Returns the number of currently pending requests.
   * Useful for debugging and monitoring request deduplication.
   *
   * @returns The count of pending requests
   */
  static getPendingRequestsCount(): number {
    return this.pendingRequests.size;
  }

  /**
   * Clears all pending requests from the cache.
   * This method is primarily intended for testing purposes.
   *
   * @warning Use with caution in production as this will affect all pending requests
   */
  static clearAllPendingRequests(): void {
    this.pendingRequests.clear();
  }

  /**
   * Checks if a request with the given cache key is currently pending.
   *
   * @param cacheKey - The cache key to check
   * @returns true if a request with this cache key is pending, false otherwise
   */
  static hasPendingRequest(cacheKey: string): boolean {
    return this.pendingRequests.has(cacheKey);
  }
}
