import ts from 'typescript';

export function printOpenapiTs(nodes: ts.Node[]): string {
  // TypeScript Printer를 사용하여 synthesized node 문제 해결
  const printer = ts.createPrinter({
    newLine: ts.NewLineKind.LineFeed,
    removeComments: false,
  });

  // SourceFile 생성 (synthesized node를 위해 필요)
  const sourceFile = ts.createSourceFile(
    'generated.ts',
    '',
    ts.ScriptTarget.Latest,
    false,
    ts.ScriptKind.TS,
  );

  // Printer를 사용하여 각 노드를 문자열로 변환
  const sourceCode = nodes
    .map((node) => printer.printNode(ts.EmitHint.Unspecified, node, sourceFile))
    .join('\n');

  const header = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */\n`;

  return [header, sourceCode].join('\n');
}
