import ts from "typescript";
import { randomFilename } from "#tools/randomFilename.js";

export function renderOpenapiTs(nodes: ts.Node[]): string {
  // Use the TypeScript printer to handle synthesized nodes.
  const printer = ts.createPrinter({
    newLine: ts.NewLineKind.LineFeed,
    removeComments: false,
  });

  // Create a source file for synthesized nodes.
  const filename = randomFilename();
  const sourceFile = ts.createSourceFile(filename, "", ts.ScriptTarget.Latest, false, ts.ScriptKind.TS);

  // Print each node through the TypeScript printer.
  const sourceCode = nodes.map((node) => printer.printNode(ts.EmitHint.Unspecified, node, sourceFile)).join("\n");

  const header = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */\n`;

  return [header, sourceCode].join("\n");
}
