import type { ArgsDef } from "citty";
import { generatorOptionArgs } from "#schema/args/generatorOptionArgs.js";
import { openapiTypeScriptOptionArgs } from "#schema/args/openapiTypeScriptOptionArgs.js";

export const frameCommandArgs = {
  ...generatorOptionArgs,
  ...openapiTypeScriptOptionArgs,
  type: {
    type: "string",
    alias: "t",
    required: true,
    description: "Path to the TypeScript type definition file generated by openapi-typescript",
  },
} satisfies ArgsDef;
